// Quiz data containing antonyms and synonyms with meanings
export const quizData = {
  antonyms: [
    { word: "abate", meaning: "to reduce in intensity or amount", options: ["vague", "definite", "modest", "intensify"], correct: 3 },
    { word: "aberration", meaning: "a departure from what is normal or expected", options: ["normality", "selfish", "thorough", "abundance"], correct: 0 },
    { word: "abhor", meaning: "to regard with disgust and hatred", options: ["exciting", "admire", "indulge", "unproductive"], correct: 1 },
    { word: "abstain", meaning: "to restrain oneself from indulging in something", options: ["honesty", "cowardly", "indulge", "extraordinary"], correct: 2 },
    { word: "acquiesce", meaning: "to accept something reluctantly without protest", options: ["neglect", "convict", "oppose", "depressed"], correct: 2 },
    { word: "adamant", meaning: "refusing to be persuaded or to change one's mind", options: ["virtuous", "flexible", "aggravate", "malevolent"], correct: 1 },
    { word: "altruistic", meaning: "showing selfless concern for the well-being of others", options: ["industrious", "apathetic", "selfish", "petty"], correct: 2 },
    { word: "ambiguous", meaning: "open to more than one interpretation; not clear", options: ["clear", "modern", "wordy", "unlikely"], correct: 0 },
    { word: "ameliorate", meaning: "to make better or improve", options: ["worsen", "petty", "enthusiastic", "modest"], correct: 0 },
    { word: "apathetic", meaning: "showing no interest or enthusiasm", options: ["enthusiastic", "miserable", "provoke", "cowardly"], correct: 0 },
    { word: "arrogant", meaning: "having an exaggerated sense of one's own importance", options: ["humble", "apathetic", "agitation", "truthful"], correct: 0 },
    { word: "audacious", meaning: "showing willingness to take bold risks", options: ["originality", "timid", "respect", "energize"], correct: 1 },
    { word: "austere", meaning: "severe or strict in manner or attitude", options: ["luxurious", "modest", "narrow", "hidden"], correct: 0 },
    { word: "benevolent", meaning: "well-meaning and kindly", options: ["originality", "common", "virtuous", "malevolent"], correct: 3 },
    { word: "brevity", meaning: "concise and exact use of words", options: ["lengthiness", "extraordinary", "harmful", "respect"], correct: 0 },
    { word: "cacophony", meaning: "a harsh, discordant mixture of sounds", options: ["excellent", "generosity", "harmony", "malevolent"], correct: 2 },
    { word: "capricious", meaning: "given to sudden changes of mood or behavior", options: ["consistent", "respect", "changeable", "original"], correct: 0 },
    { word: "circumspect", meaning: "wary and unwilling to take risks", options: ["preserve", "hidden", "disrespect", "reckless"], correct: 3 },
    { word: "coerce", meaning: "to persuade using force or threats", options: ["persuade", "normality", "wordy", "indulge"], correct: 0 },
    { word: "concise", meaning: "giving a lot of information clearly in few words", options: ["honesty", "sloppy", "wordy", "preserve"], correct: 2 },
    { word: "concur", meaning: "to be of the same opinion; agree", options: ["disagree", "honesty", "excellent", "seriousness"], correct: 0 },
    { word: "conspicuous", meaning: "clearly visible; attracting notice", options: ["lazy", "moral", "hidden", "timid"], correct: 2 },
    { word: "contrite", meaning: "feeling or expressing remorse", options: ["seriousness", "serious", "unrepentant", "abundance"], correct: 2 },
    { word: "copious", meaning: "abundant in supply or quantity", options: ["industrious", "luxurious", "scarce", "taciturn"], correct: 2 },
    { word: "cryptic", meaning: "having a meaning that is mysterious or obscure", options: ["consistent", "cowardly", "obvious", "beneficial"], correct: 2 },
    { word: "cursory", meaning: "hasty and superficial", options: ["oppose", "wordy", "generosity", "thorough"], correct: 3 },
    { word: "dauntless", meaning: "showing fearlessness and determination", options: ["cowardly", "timid", "overlook", "unlikely"], correct: 0 },
    { word: "dearth", meaning: "a scarcity or lack of something", options: ["malevolent", "common", "exciting", "abundance"], correct: 3 },
    { word: "debacle", meaning: "a sudden and ignominious failure", options: ["competent", "success", "unrepentant", "apathetic"], correct: 1 },
    { word: "decadent", meaning: "morally degenerate", options: ["moral", "clear", "serious", "generosity"], correct: 0 },
    { word: "deference", meaning: "humble submission and respect", options: ["careless", "lazy", "disrespect", "timid"], correct: 2 },
    { word: "deleterious", meaning: "causing harm or damage", options: ["disagree", "apathetic", "beneficial", "obvious"], correct: 2 },
    { word: "diligent", meaning: "having or showing care in one's work or duties", options: ["indulge", "lazy", "famous", "harmless"], correct: 1 },
    { word: "discern", meaning: "to perceive or recognize", options: ["energize", "changeable", "convict", "overlook"], correct: 3 },
    { word: "disdain", meaning: "the feeling that someone is unworthy of consideration", options: ["vague", "scarce", "serious", "respect"], correct: 3 },
    { word: "disparage", meaning: "to regard or represent as being of little worth", options: ["reckless", "cheerful", "original", "praise"], correct: 3 },
    { word: "docile", meaning: "ready to accept control or instruction", options: ["timid", "stubborn", "lazy", "cheerful"], correct: 1 },
    { word: "dormant", meaning: "temporarily inactive", options: ["original", "active", "moral", "respect"], correct: 1 },
    { word: "ebullient", meaning: "cheerful and full of energy", options: ["introverted", "depressed", "definite", "agitation"], correct: 1 },
    { word: "eclectic", meaning: "deriving ideas from a broad range of sources", options: ["disrespect", "narrow", "consistent", "changeable"], correct: 1 },
    { word: "efface", meaning: "to erase or remove from surface or memory", options: ["unrepentant", "beneficial", "preserve", "modern"], correct: 2 },
    { word: "elated", meaning: "very happy and excited", options: ["calm", "excellent", "original", "miserable"], correct: 3 },
    { word: "eloquent", meaning: "fluent and persuasive in speaking or writing", options: ["inarticulate", "indulge", "normality", "lazy"], correct: 0 },
    { word: "emulate", meaning: "to match or surpass by imitation", options: ["neglect", "calm", "obvious", "aggravate"], correct: 0 },
    { word: "enervate", meaning: "to cause to feel drained of energy", options: ["consistent", "careless", "agitation", "energize"], correct: 3 },
    { word: "ephemeral", meaning: "lasting for a very short time", options: ["hinder", "clear", "depressed", "permanent"], correct: 3 },
    { word: "equanimity", meaning: "mental calmness and composure", options: ["lengthiness", "virtuous", "industrious", "agitation"], correct: 3 },
    { word: "equivocal", meaning: "open to more than one interpretation", options: ["definite", "excellent", "humble", "yielding"], correct: 0 },
    { word: "esoteric", meaning: "intended for or understood by a small group", options: ["sloppy", "worsen", "common", "reckless"], correct: 2 },
    { word: "evanescent", meaning: "soon passing out of sight or memory", options: ["indulge", "enduring", "industrious", "changeable"], correct: 1 },
    { word: "exacerbate", meaning: "to make a problem or bad situation worse", options: ["benevolent", "alleviate", "originality", "unproductive"], correct: 1 },
    { word: "exonerate", meaning: "to absolve from blame for a fault or wrongdoing", options: ["convict", "secure", "alleviate", "miserable"], correct: 0 },
    { word: "facilitate", meaning: "to make an action or process easier", options: ["luxurious", "lazy", "hinder", "aggravate"], correct: 2 },
    { word: "fallacious", meaning: "based on a mistaken belief", options: ["excellent", "truthful", "modest", "changeable"], correct: 1 },
    { word: "fastidious", meaning: "very attentive to accuracy and detail", options: ["careless", "verbose", "humble", "enduring"], correct: 0 },
    { word: "fervent", meaning: "having or displaying great intensity of feeling", options: ["apathetic", "indulge", "worsen", "overlook"], correct: 0 },
    { word: "flagrant", meaning: "conspicuously and outrageously bad", options: ["respectful", "subtle", "alleviate", "humble"], correct: 1 },
    { word: "fortuitous", meaning: "happening by accident or chance", options: ["intentional", "secure", "cheerful", "yielding"], correct: 0 },
    { word: "frivolous", meaning: "not having any serious purpose or value", options: ["modest", "luxurious", "introverted", "serious"], correct: 3 },
    { word: "furtive", meaning: "attempting to avoid notice", options: ["open", "preserve", "miserable", "normality"], correct: 0 },
    { word: "garrulous", meaning: "excessively talkative", options: ["neglect", "taciturn", "modest", "disrespect"], correct: 1 },
    { word: "gregarious", meaning: "fond of the company of others", options: ["introverted", "overlook", "humble", "unlikely"], correct: 0 },
    { word: "guile", meaning: "sly or cunning intelligence", options: ["persuade", "moral", "honesty", "modest"], correct: 2 },
    { word: "hackneyed", meaning: "overused and therefore lacking originality", options: ["verbose", "original", "abundance", "inarticulate"], correct: 1 },
    { word: "haughty", meaning: "arrogantly superior and disdainful", options: ["cautious", "yielding", "unrepentant", "modest"], correct: 3 },
    { word: "immutable", meaning: "unchanging over time or unable to be changed", options: ["changeable", "enduring", "originality", "scarce"], correct: 0 },
    { word: "impetuous", meaning: "acting quickly without thought or care", options: ["harmony", "luxurious", "easy", "cautious"], correct: 3 },
    { word: "implacable", meaning: "unable to be appeased", options: ["neutral", "yielding", "lengthiness", "malevolent"], correct: 1 },
    { word: "impudent", meaning: "not showing due respect; impertinent", options: ["timid", "famous", "verbose", "respectful"], correct: 3 },
    { word: "inadvertent", meaning: "done without conscious intention", options: ["virtuous", "moral", "benevolent", "intentional"], correct: 3 },
    { word: "incisive", meaning: "accurately analytical; clear-cut", options: ["vague", "fallible", "hinder", "obvious"], correct: 0 },
    { word: "indolent", meaning: "wanting to avoid activity or exertion; lazy", options: ["agitation", "neutral", "easy", "industrious"], correct: 3 },
    { word: "inept", meaning: "showing no skill; clumsy", options: ["luxurious", "neglect", "extraordinary", "competent"], correct: 3 },
    { word: "infallible", meaning: "incapable of making mistakes", options: ["worsen", "industrious", "fallible", "inarticulate"], correct: 2 },
    { word: "innocuous", meaning: "not harmful or offensive", options: ["harmful", "miserable", "fallible", "provoke"], correct: 0 },
    { word: "insipid", meaning: "lacking flavor; lacking vigor or interest", options: ["calm", "exciting", "enduring", "intensify"], correct: 1 },
    { word: "intrepid", meaning: "fearless; adventurous", options: ["abundance", "aggravate", "enduring", "fearful"], correct: 3 },
    { word: "irate", meaning: "feeling or showing extreme anger", options: ["calm", "clear", "petty", "harmful"], correct: 0 },
    { word: "laconic", meaning: "using few words; expressing much in few words", options: ["verbose", "secure", "overlook", "careless"], correct: 0 },
    { word: "languid", meaning: "lacking energy or vitality", options: ["honesty", "industrious", "energetic", "serious"], correct: 2 },
    { word: "levity", meaning: "treatment of a serious matter with humor", options: ["seriousness", "introverted", "indulge", "miserable"], correct: 0 },
    { word: "lucid", meaning: "expressed clearly; easy to understand", options: ["narrow", "confusing", "subtle", "permanent"], correct: 1 },
    { word: "magnanimous", meaning: "generous in forgiving; noble in spirit", options: ["stubborn", "petty", "seriousness", "careless"], correct: 1 },
    { word: "malevolent", meaning: "having or showing a wish to do evil to others", options: ["depressed", "benevolent", "intentional", "introverted"], correct: 1 },
    { word: "mediocre", meaning: "of moderate quality; not very good", options: ["modest", "scarce", "virtuous", "excellent"], correct: 3 },
    { word: "meticulous", meaning: "showing great attention to detail", options: ["depressed", "definite", "sloppy", "modest"], correct: 2 },
    { word: "mitigate", meaning: "to make less severe or serious", options: ["aggravate", "intentional", "confusing", "scarce"], correct: 0 },
    { word: "morose", meaning: "bad-tempered and sulky", options: ["verbose", "cheerful", "preserve", "generosity"], correct: 1 },
    { word: "mundane", meaning: "lacking interest or excitement; ordinary", options: ["extraordinary", "selfish", "stubborn", "clear"], correct: 0 },
    { word: "nefarious", meaning: "extremely wicked", options: ["clear", "energetic", "virtuous", "generosity"], correct: 2 },
    { word: "obdurate", meaning: "stubbornly refusing to change", options: ["yielding", "indulge", "exciting", "generosity"], correct: 0 },
    { word: "obscure", meaning: "not discovered or known about", options: ["famous", "generosity", "scarce", "neglect"], correct: 0 },
    { word: "obsolete", meaning: "no longer produced or used; out of date", options: ["stubborn", "modern", "unproductive", "oppose"], correct: 1 },
    { word: "onerous", meaning: "involving a great deal of effort or difficulty", options: ["persuade", "easy", "indulge", "thorough"], correct: 1 },
    { word: "ostentatious", meaning: "designed to impress or attract notice", options: ["originality", "alleviate", "modest", "abundance"], correct: 2 },
    { word: "parsimony", meaning: "extreme frugality; reluctance to spend", options: ["competent", "extraordinary", "generosity", "verbose"], correct: 2 },
    { word: "partisan", meaning: "prejudiced in favor of a particular cause", options: ["agitation", "stubborn", "persuade", "neutral"], correct: 3 },
    { word: "penchant", meaning: "a strong or habitual liking", options: ["dislike", "secure", "originality", "modern"], correct: 0 },
    { word: "perfunctory", meaning: "carried out with minimum effort", options: ["thorough", "malevolent", "intensify", "open"], correct: 0 },
    { word: "pernicious", meaning: "having a harmful effect in a gradual way", options: ["reckless", "harmless", "stubborn", "easy"], correct: 1 },
    { word: "placate", meaning: "to make someone less angry or hostile", options: ["originality", "disagree", "provoke", "changeable"], correct: 2 },
    { word: "platitude", meaning: "a remark that has been used too often", options: ["overlook", "harmful", "respect", "originality"], correct: 3 },
    { word: "plausible", meaning: "seeming reasonable or probable", options: ["subtle", "abundance", "unlikely", "virtuous"], correct: 2 },
    { word: "precarious", meaning: "not securely held; uncertain", options: ["aggravate", "secure", "oppose", "apathetic"], correct: 1 },
    { word: "prolific", meaning: "producing many works or results", options: ["unproductive", "modern", "extraordinary", "famous"], correct: 0 }
  ],
  synonyms: [
    { word: "abstruse", meaning: "difficult to understand; obscure", options: ["simple", "common", "clear", "obscure"], correct: 3 },
    { word: "recalcitrant", meaning: "having an obstinately uncooperative attitude", options: ["obedient", "compliant", "docile", "stubborn"], correct: 3 },
    { word: "pernicious", meaning: "having a harmful effect, especially gradually", options: ["harmless", "kind", "beneficial", "deadly"], correct: 3 },
    { word: "obfuscate", meaning: "to render obscure, unclear, or unintelligible", options: ["clarify", "explain", "simplify", "confuse"], correct: 3 },
    { word: "excoriate", meaning: "to criticize severely", options: ["praise", "honor", "reward", "criticize"], correct: 3 },
    { word: "sycophant", meaning: "a person who acts obsequiously to gain advantage", options: ["leader", "critic", "follower", "flatterer"], correct: 3 },
    { word: "pulchritude", meaning: "physical beauty", options: ["ugliness", "anger", "cruelty", "beauty"], correct: 3 },
    { word: "obdurate", meaning: "stubbornly refusing to change one's opinion", options: ["flexible", "yielding", "soft", "stubborn"], correct: 3 },
    { word: "recondite", meaning: "little known; abstruse", options: ["familiar", "clear", "popular", "arcane"], correct: 3 },
    { word: "insouciant", meaning: "showing a casual lack of concern", options: ["worried", "concerned", "anxious", "carefree"], correct: 3 },
    { word: "vituperate", meaning: "to blame or insult someone in strong terms", options: ["compliment", "support", "ignore", "insult"], correct: 3 },
    { word: "lugubrious", meaning: "looking or sounding sad and dismal", options: ["joyful", "happy", "cheerful", "mournful"], correct: 3 },
    { word: "inveterate", meaning: "having a particular habit, activity, or interest that is long-established", options: ["occasional", "temporary", "unusual", "habitual"], correct: 3 },
    { word: "indefatigable", meaning: "persisting tirelessly", options: ["tired", "weary", "lazy", "energetic"], correct: 3 },
    { word: "contumacious", meaning: "stubbornly or willfully disobedient to authority", options: ["obedient", "submissive", "compliant", "defiant"], correct: 3 },
    { word: "quixotic", meaning: "extremely idealistic and unrealistic", options: ["practical", "realistic", "logical", "idealistic"], correct: 3 },
    { word: "nugatory", meaning: "of no value or importance", options: ["important", "valuable", "meaningful", "trivial"], correct: 3 },
    { word: "pusillanimous", meaning: "showing a lack of courage or determination", options: ["brave", "bold", "courageous", "fearful"], correct: 3 },
    { word: "apocryphal", meaning: "of doubtful authenticity", options: ["genuine", "authentic", "valid", "fake"], correct: 3 },
    { word: "sanguine", meaning: "optimistic or positive, especially in a difficult situation", options: ["pessimistic", "sad", "depressed", "optimistic"], correct: 3 },
    { word: "intransigent", meaning: "unwilling or refusing to change one's views", options: ["yielding", "submissive", "obedient", "uncompromising"], correct: 3 },
    { word: "munificent", meaning: "very generous", options: ["greedy", "stingy", "frugal", "generous"], correct: 3 },
    { word: "ubiquitous", meaning: "present, appearing, or found everywhere", options: ["rare", "scarce", "singular", "omnipresent"], correct: 3 },
    { word: "vicissitude", meaning: "a natural change or mutation visible in nature", options: ["stability", "routine", "consistency", "change"], correct: 3 },
    { word: "desuetude", meaning: "a state of disuse", options: ["use", "tradition", "custom", "disuse"], correct: 3 },
    { word: "truculent", meaning: "eager or quick to argue or fight", options: ["friendly", "peaceful", "passive", "aggressive"], correct: 3 },
    { word: "pellucid", meaning: "transparently clear; easily understood", options: ["vague", "dim", "faint", "clear"], correct: 3 },
    { word: "obeisance", meaning: "deferential respect", options: ["disrespect", "rudeness", "indifference", "respect"], correct: 3 },
    { word: "exiguous", meaning: "very small in size or amount", options: ["abundant", "excessive", "generous", "scanty"], correct: 3 },
    { word: "mendacious", meaning: "given to lying", options: ["honest", "truthful", "sincere", "deceitful"], correct: 3 },
    { word: "alacrity", meaning: "brisk and cheerful readiness", options: ["laziness", "slowness", "reluctance", "eagerness"], correct: 3 },
    { word: "impetuous", meaning: "acting or done quickly and without thought", options: ["cautious", "calm", "slow", "rash"], correct: 3 },
    { word: "probity", meaning: "integrity and uprightness; honesty", options: ["dishonesty", "trickery", "fraud", "integrity"], correct: 3 },
    { word: "inchoate", meaning: "just begun and not fully formed", options: ["mature", "complete", "final", "unformed"], correct: 3 },
    { word: "pernickety", meaning: "placing too much emphasis on trivial details", options: ["careless", "casual", "lazy", "fussy"], correct: 3 },
    { word: "sagacious", meaning: "having good judgment", options: ["silly", "foolish", "unwise", "wise"], correct: 3 },
    { word: "garrulous", meaning: "excessively talkative", options: ["quiet", "mute", "silent", "talkative"], correct: 3 },
    { word: "cacophony", meaning: "a harsh, discordant mixture of sounds", options: ["melody", "harmony", "silence", "discord"], correct: 3 },
    { word: "cupidity", meaning: "greed for money or possessions", options: ["generosity", "kindness", "charity", "greed"], correct: 3 },
    { word: "disconsolate", meaning: "without consolation or comfort; unhappy", options: ["happy", "joyful", "cheerful", "unhappy"], correct: 3 },
    { word: "tenebrous", meaning: "dark; shadowy or obscure", options: ["bright", "clear", "luminous", "dark"], correct: 3 },
    { word: "lachrymose", meaning: "tearful or given to weeping", options: ["joyful", "happy", "dry", "tearful"], correct: 3 },
    { word: "rebarbative", meaning: "unattractive and objectionable", options: ["charming", "attractive", "pleasant", "offensive"], correct: 3 },
    { word: "dilatory", meaning: "slow to act", options: ["prompt", "speedy", "quick", "slow"], correct: 3 },
    { word: "turpitude", meaning: "depravity; wickedness", options: ["virtue", "honor", "decency", "depravity"], correct: 3 },
    { word: "ebullient", meaning: "cheerful and full of energy", options: ["gloomy", "depressed", "sad", "exuberant"], correct: 3 },
    { word: "parsimonious", meaning: "extremely frugal; unwilling to spend", options: ["generous", "lavish", "extravagant", "frugal"], correct: 3 },
    { word: "sagacity", meaning: "the quality of being sagacious", options: ["foolishness", "ignorance", "stupidity", "wisdom"], correct: 3 },
    { word: "esoteric", meaning: "intended for or likely to be understood by only a small number", options: ["obvious", "common", "clear", "arcane"], correct: 3 },
    { word: "lissome", meaning: "thin, supple, and graceful", options: ["clumsy", "awkward", "stiff", "graceful"], correct: 3 },
    { word: "ineffable", meaning: "too great or extreme to be expressed in words", options: ["expressible", "loud", "talkative", "indescribable"], correct: 3 },
    { word: "redolent", meaning: "strongly reminiscent or suggestive of", options: ["fragrant", "odorless", "dull", "quiet"], correct: 0 },
    { word: "enervate", meaning: "to cause to feel drained of energy or vitality", options: ["strengthen", "energize", "weaken", "inspire"], correct: 2 },
    { word: "perfunctory", meaning: "carried out with a minimum of effort", options: ["thorough", "detailed", "mechanical", "intentional"], correct: 2 },
    { word: "abrogate", meaning: "to repeal or do away with", options: ["approve", "repeal", "support", "enforce"], correct: 1 },
    { word: "expiate", meaning: "to make amends for", options: ["offend", "ignore", "atone", "refuse"], correct: 2 },
    { word: "celerity", meaning: "swiftness of movement", options: ["delay", "swiftness", "stillness", "weakness"], correct: 1 },
    { word: "timorous", meaning: "showing or suffering from nervousness", options: ["fearful", "brave", "assertive", "loud"], correct: 0 },
    { word: "refulgent", meaning: "shining very brightly", options: ["dark", "faded", "shining", "dull"], correct: 2 },
    { word: "obsequious", meaning: "obedient or attentive to an excessive degree", options: ["defiant", "dominant", "servile", "bold"], correct: 2 },
    { word: "penurious", meaning: "extremely poor; poverty-stricken", options: ["wealthy", "poor", "lavish", "happy"], correct: 1 },
    { word: "callow", meaning: "young and inexperienced", options: ["inexperienced", "mature", "old", "skilled"], correct: 0 },
    { word: "turgid", meaning: "swollen and distended or congested", options: ["simple", "pompous", "plain", "small"], correct: 1 },
    { word: "mawkish", meaning: "sentimental in a feeble or sickly way", options: ["bitter", "sour", "sentimental", "rude"], correct: 2 },
    { word: "hegemony", meaning: "leadership or dominance", options: ["weakness", "domination", "freedom", "tolerance"], correct: 1 },
    { word: "solipsistic", meaning: "characterized by extreme preoccupation with oneself", options: ["generous", "empathic", "self-centered", "social"], correct: 2 },
    { word: "acerbic", meaning: "sharp and forthright", options: ["sweet", "harsh", "polite", "silent"], correct: 1 },
    { word: "antediluvian", meaning: "of or belonging to the time before the flood", options: ["modern", "ancient", "future", "youthful"], correct: 1 },
    { word: "supercilious", meaning: "behaving as though one thinks they are superior", options: ["arrogant", "humble", "honest", "shy"], correct: 0 },
    { word: "phlegmatic", meaning: "having an unemotional and stolidly calm disposition", options: ["calm", "energetic", "nervous", "angry"], correct: 0 },
    { word: "fastidious", meaning: "very attentive to accuracy and detail", options: ["sloppy", "meticulous", "lazy", "rash"], correct: 1 },
    { word: "prolix", meaning: "using too many words; tediously lengthy", options: ["brief", "wordy", "concise", "silent"], correct: 1 },
    { word: "vicissitude", meaning: "the natural changes and mutations of life", options: ["fluctuation", "calm", "consistency", "stability"], correct: 0 },
    { word: "invidious", meaning: "likely to arouse resentment in others", options: ["fair", "offensive", "honest", "pleasant"], correct: 1 },
    { word: "pell-mell", meaning: "in a confused, rushed, or disorderly manner", options: ["orderly", "chaotic", "calm", "careful"], correct: 1 },
    { word: "lambaste", meaning: "to criticize harshly", options: ["criticize", "praise", "encourage", "embrace"], correct: 0 },
    { word: "umbrage", meaning: "offense or annoyance", options: ["joy", "offense", "laughter", "silence"], correct: 1 },
    { word: "inure", meaning: "to accustom someone to something unpleasant", options: ["surprise", "accustom", "reject", "resist"], correct: 1 },
    { word: "apogee", meaning: "the highest point in the development of something", options: ["bottom", "peak", "decline", "base"], correct: 1 },
    { word: "obviate", meaning: "to remove a need or difficulty", options: ["complicate", "prevent", "induce", "permit"], correct: 1 },
    { word: "gainsay", meaning: "to deny or contradict", options: ["confirm", "deny", "repeat", "support"], correct: 1 },
    { word: "feckless", meaning: "lacking initiative or strength of character", options: ["responsible", "ineffective", "helpful", "dynamic"], correct: 1 },
    { word: "largesse", meaning: "generosity in bestowing money or gifts", options: ["avarice", "generosity", "greed", "theft"], correct: 1 },
    { word: "ribald", meaning: "referring to sexual matters in an amusingly rude way", options: ["clean", "vulgar", "honest", "gentle"], correct: 1 },
    { word: "trenchant", meaning: "vigorous or incisive in expression or style", options: ["sharp", "dull", "weak", "blunt"], correct: 0 },
    { word: "equanimity", meaning: "mental calmness and composure", options: ["rage", "composure", "excitement", "sadness"], correct: 1 },
    { word: "perspicacious", meaning: "having keen insight; mentally sharp", options: ["dull", "insightful", "slow", "confused"], correct: 1 },
    { word: "ascetic", meaning: "characterized by severe self-discipline", options: ["self-disciplined", "hedonistic", "lazy", "carefree"], correct: 0 },
    { word: "adumbrate", meaning: "to report or represent in outline", options: ["foreshadow", "explain", "deny", "outline"], correct: 0 },
    { word: "noisome", meaning: "having an extremely offensive smell", options: ["pleasant", "offensive", "mild", "harmless"], correct: 1 },
    { word: "verisimilitude", meaning: "the appearance of being true or real", options: ["lie", "fiction", "authenticity", "deception"], correct: 2 },
    { word: "invective", meaning: "insulting, abusive, or highly critical language", options: ["praise", "abuse", "logic", "reason"], correct: 1 },
    { word: "dissemble", meaning: "to conceal one's true motives or feelings", options: ["reveal", "conceal", "admit", "confess"], correct: 1 },
    { word: "propinquity", meaning: "nearness in place or time", options: ["distance", "division", "nearness", "disparity"], correct: 2 },
    { word: "abstemious", meaning: "indulging only very moderately", options: ["lavish", "moderate", "greedy", "excessive"], correct: 1 },
    { word: "recondite", meaning: "little known; abstruse", options: ["simple", "obscure", "clear", "obvious"], correct: 1 },
    { word: "noxious", meaning: "harmful, poisonous, or very unpleasant", options: ["harmful", "healing", "weak", "helpful"], correct: 0 },
    { word: "desultory", meaning: "lacking a plan, purpose, or enthusiasm", options: ["focused", "careful", "aimless", "steady"], correct: 2 },
    { word: "soporific", meaning: "tending to induce drowsiness or sleep", options: ["sleep-inducing", "exciting", "energizing", "noisy"], correct: 0 },
    { word: "inept", meaning: "showing no skill; clumsy", options: ["clumsy", "skilled", "clever", "efficient"], correct: 0 }
  ]
};
