// Quiz data containing antonyms and synonyms with meanings
export const quizData = {
  antonyms: [
    { word: "abate", meaning: "to reduce in intensity or amount", options: ["vague", "definite", "modest", "intensify"], correct: 3 },
    { word: "aberration", meaning: "a departure from what is normal or expected", options: ["normality", "selfish", "thorough", "abundance"], correct: 0 },
    { word: "abhor", meaning: "to regard with disgust and hatred", options: ["exciting", "admire", "indulge", "unproductive"], correct: 1 },
    { word: "abstain", meaning: "to restrain oneself from indulging in something", options: ["honesty", "cowardly", "indulge", "extraordinary"], correct: 2 },
    { word: "acquiesce", meaning: "to accept something reluctantly without protest", options: ["neglect", "convict", "oppose", "depressed"], correct: 2 },
    { word: "adamant", meaning: "refusing to be persuaded or to change one's mind", options: ["virtuous", "flexible", "aggravate", "malevolent"], correct: 1 },
    { word: "altruistic", meaning: "showing selfless concern for the well-being of others", options: ["industrious", "apathetic", "selfish", "petty"], correct: 2 },
    { word: "ambiguous", meaning: "open to more than one interpretation; not clear", options: ["clear", "modern", "wordy", "unlikely"], correct: 0 },
    { word: "ameliorate", meaning: "to make better or improve", options: ["worsen", "petty", "enthusiastic", "modest"], correct: 0 },
    { word: "apathetic", meaning: "showing no interest or enthusiasm", options: ["enthusiastic", "miserable", "provoke", "cowardly"], correct: 0 },
    { word: "arrogant", meaning: "having an exaggerated sense of one's own importance", options: ["humble", "apathetic", "agitation", "truthful"], correct: 0 },
    { word: "audacious", meaning: "showing willingness to take bold risks", options: ["originality", "timid", "respect", "energize"], correct: 1 },
    { word: "austere", meaning: "severe or strict in manner or attitude", options: ["luxurious", "modest", "narrow", "hidden"], correct: 0 },
    { word: "benevolent", meaning: "well-meaning and kindly", options: ["originality", "common", "virtuous", "malevolent"], correct: 3 },
    { word: "brevity", meaning: "concise and exact use of words", options: ["lengthiness", "extraordinary", "harmful", "respect"], correct: 0 },
    { word: "cacophony", meaning: "a harsh, discordant mixture of sounds", options: ["excellent", "generosity", "harmony", "malevolent"], correct: 2 },
    { word: "capricious", meaning: "given to sudden changes of mood or behavior", options: ["consistent", "respect", "changeable", "original"], correct: 0 },
    { word: "circumspect", meaning: "wary and unwilling to take risks", options: ["preserve", "hidden", "disrespect", "reckless"], correct: 3 },
    { word: "coerce", meaning: "to persuade using force or threats", options: ["persuade", "normality", "wordy", "indulge"], correct: 0 },
    { word: "concise", meaning: "giving a lot of information clearly in few words", options: ["honesty", "sloppy", "wordy", "preserve"], correct: 2 },
    { word: "concur", meaning: "to be of the same opinion; agree", options: ["disagree", "honesty", "excellent", "seriousness"], correct: 0 },
    { word: "conspicuous", meaning: "clearly visible; attracting notice", options: ["lazy", "moral", "hidden", "timid"], correct: 2 },
    { word: "contrite", meaning: "feeling or expressing remorse", options: ["seriousness", "serious", "unrepentant", "abundance"], correct: 2 },
    { word: "copious", meaning: "abundant in supply or quantity", options: ["industrious", "luxurious", "scarce", "taciturn"], correct: 2 },
    { word: "cryptic", meaning: "having a meaning that is mysterious or obscure", options: ["consistent", "cowardly", "obvious", "beneficial"], correct: 2 },
    { word: "cursory", meaning: "hasty and superficial", options: ["oppose", "wordy", "generosity", "thorough"], correct: 3 },
    { word: "dauntless", meaning: "showing fearlessness and determination", options: ["cowardly", "timid", "overlook", "unlikely"], correct: 0 },
    { word: "dearth", meaning: "a scarcity or lack of something", options: ["malevolent", "common", "exciting", "abundance"], correct: 3 },
    { word: "debacle", meaning: "a sudden and ignominious failure", options: ["competent", "success", "unrepentant", "apathetic"], correct: 1 },
    { word: "decadent", meaning: "morally degenerate", options: ["moral", "clear", "serious", "generosity"], correct: 0 },
    { word: "deference", meaning: "humble submission and respect", options: ["careless", "lazy", "disrespect", "timid"], correct: 2 },
    { word: "deleterious", meaning: "causing harm or damage", options: ["disagree", "apathetic", "beneficial", "obvious"], correct: 2 },
    { word: "diligent", meaning: "having or showing care in one's work or duties", options: ["indulge", "lazy", "famous", "harmless"], correct: 1 },
    { word: "discern", meaning: "to perceive or recognize", options: ["energize", "changeable", "convict", "overlook"], correct: 3 },
    { word: "disdain", meaning: "the feeling that someone is unworthy of consideration", options: ["vague", "scarce", "serious", "respect"], correct: 3 },
    { word: "disparage", meaning: "to regard or represent as being of little worth", options: ["reckless", "cheerful", "original", "praise"], correct: 3 },
    { word: "docile", meaning: "ready to accept control or instruction", options: ["timid", "stubborn", "lazy", "cheerful"], correct: 1 },
    { word: "dormant", meaning: "temporarily inactive", options: ["original", "active", "moral", "respect"], correct: 1 },
    { word: "ebullient", meaning: "cheerful and full of energy", options: ["introverted", "depressed", "definite", "agitation"], correct: 1 },
    { word: "eclectic", meaning: "deriving ideas from a broad range of sources", options: ["disrespect", "narrow", "consistent", "changeable"], correct: 1 },
    { word: "efface", meaning: "to erase or remove from surface or memory", options: ["unrepentant", "beneficial", "preserve", "modern"], correct: 2 },
    { word: "elated", meaning: "very happy and excited", options: ["calm", "excellent", "original", "miserable"], correct: 3 },
    { word: "eloquent", meaning: "fluent and persuasive in speaking or writing", options: ["inarticulate", "indulge", "normality", "lazy"], correct: 0 },
    { word: "emulate", meaning: "to match or surpass by imitation", options: ["neglect", "calm", "obvious", "aggravate"], correct: 0 },
    { word: "enervate", meaning: "to cause to feel drained of energy", options: ["consistent", "careless", "agitation", "energize"], correct: 3 },
    { word: "ephemeral", meaning: "lasting for a very short time", options: ["hinder", "clear", "depressed", "permanent"], correct: 3 },
    { word: "equanimity", meaning: "mental calmness and composure", options: ["lengthiness", "virtuous", "industrious", "agitation"], correct: 3 },
    { word: "equivocal", meaning: "open to more than one interpretation", options: ["definite", "excellent", "humble", "yielding"], correct: 0 },
    { word: "esoteric", meaning: "intended for or understood by a small group", options: ["sloppy", "worsen", "common", "reckless"], correct: 2 },
    { word: "evanescent", meaning: "soon passing out of sight or memory", options: ["indulge", "enduring", "industrious", "changeable"], correct: 1 },
    { word: "exacerbate", meaning: "to make a problem or bad situation worse", options: ["benevolent", "alleviate", "originality", "unproductive"], correct: 1 },
    { word: "exonerate", meaning: "to absolve from blame for a fault or wrongdoing", options: ["convict", "secure", "alleviate", "miserable"], correct: 0 },
    { word: "facilitate", meaning: "to make an action or process easier", options: ["luxurious", "lazy", "hinder", "aggravate"], correct: 2 },
    { word: "fallacious", meaning: "based on a mistaken belief", options: ["excellent", "truthful", "modest", "changeable"], correct: 1 },
    { word: "fastidious", meaning: "very attentive to accuracy and detail", options: ["careless", "verbose", "humble", "enduring"], correct: 0 },
    { word: "fervent", meaning: "having or displaying great intensity of feeling", options: ["apathetic", "indulge", "worsen", "overlook"], correct: 0 },
    { word: "flagrant", meaning: "conspicuously and outrageously bad", options: ["respectful", "subtle", "alleviate", "humble"], correct: 1 },
    { word: "fortuitous", meaning: "happening by accident or chance", options: ["intentional", "secure", "cheerful", "yielding"], correct: 0 },
    { word: "frivolous", meaning: "not having any serious purpose or value", options: ["modest", "luxurious", "introverted", "serious"], correct: 3 },
    { word: "furtive", meaning: "attempting to avoid notice", options: ["open", "preserve", "miserable", "normality"], correct: 0 },
    { word: "garrulous", meaning: "excessively talkative", options: ["neglect", "taciturn", "modest", "disrespect"], correct: 1 },
    { word: "gregarious", meaning: "fond of the company of others", options: ["introverted", "overlook", "humble", "unlikely"], correct: 0 },
    { word: "guile", meaning: "sly or cunning intelligence", options: ["persuade", "moral", "honesty", "modest"], correct: 2 },
    { word: "hackneyed", meaning: "overused and therefore lacking originality", options: ["verbose", "original", "abundance", "inarticulate"], correct: 1 },
    { word: "haughty", meaning: "arrogantly superior and disdainful", options: ["cautious", "yielding", "unrepentant", "modest"], correct: 3 },
    { word: "immutable", meaning: "unchanging over time or unable to be changed", options: ["changeable", "enduring", "originality", "scarce"], correct: 0 },
    { word: "impetuous", meaning: "acting quickly without thought or care", options: ["harmony", "luxurious", "easy", "cautious"], correct: 3 },
    { word: "implacable", meaning: "unable to be appeased", options: ["neutral", "yielding", "lengthiness", "malevolent"], correct: 1 },
    { word: "impudent", meaning: "not showing due respect; impertinent", options: ["timid", "famous", "verbose", "respectful"], correct: 3 },
    { word: "inadvertent", meaning: "done without conscious intention", options: ["virtuous", "moral", "benevolent", "intentional"], correct: 3 },
    { word: "incisive", meaning: "accurately analytical; clear-cut", options: ["vague", "fallible", "hinder", "obvious"], correct: 0 },
    { word: "indolent", meaning: "wanting to avoid activity or exertion; lazy", options: ["agitation", "neutral", "easy", "industrious"], correct: 3 },
    { word: "inept", meaning: "showing no skill; clumsy", options: ["luxurious", "neglect", "extraordinary", "competent"], correct: 3 },
    { word: "infallible", meaning: "incapable of making mistakes", options: ["worsen", "industrious", "fallible", "inarticulate"], correct: 2 },
    { word: "innocuous", meaning: "not harmful or offensive", options: ["harmful", "miserable", "fallible", "provoke"], correct: 0 },
    { word: "insipid", meaning: "lacking flavor; lacking vigor or interest", options: ["calm", "exciting", "enduring", "intensify"], correct: 1 },
    { word: "intrepid", meaning: "fearless; adventurous", options: ["abundance", "aggravate", "enduring", "fearful"], correct: 3 },
    { word: "irate", meaning: "feeling or showing extreme anger", options: ["calm", "clear", "petty", "harmful"], correct: 0 },
    { word: "laconic", meaning: "using few words; expressing much in few words", options: ["verbose", "secure", "overlook", "careless"], correct: 0 },
    { word: "languid", meaning: "lacking energy or vitality", options: ["honesty", "industrious", "energetic", "serious"], correct: 2 },
    { word: "levity", meaning: "treatment of a serious matter with humor", options: ["seriousness", "introverted", "indulge", "miserable"], correct: 0 },
    { word: "lucid", meaning: "expressed clearly; easy to understand", options: ["narrow", "confusing", "subtle", "permanent"], correct: 1 },
    { word: "magnanimous", meaning: "generous in forgiving; noble in spirit", options: ["stubborn", "petty", "seriousness", "careless"], correct: 1 },
    { word: "malevolent", meaning: "having or showing a wish to do evil to others", options: ["depressed", "benevolent", "intentional", "introverted"], correct: 1 },
    { word: "mediocre", meaning: "of moderate quality; not very good", options: ["modest", "scarce", "virtuous", "excellent"], correct: 3 },
    { word: "meticulous", meaning: "showing great attention to detail", options: ["depressed", "definite", "sloppy", "modest"], correct: 2 },
    { word: "mitigate", meaning: "to make less severe or serious", options: ["aggravate", "intentional", "confusing", "scarce"], correct: 0 },
    { word: "morose", meaning: "bad-tempered and sulky", options: ["verbose", "cheerful", "preserve", "generosity"], correct: 1 },
    { word: "mundane", meaning: "lacking interest or excitement; ordinary", options: ["extraordinary", "selfish", "stubborn", "clear"], correct: 0 },
    { word: "nefarious", meaning: "extremely wicked", options: ["clear", "energetic", "virtuous", "generosity"], correct: 2 },
    { word: "obdurate", meaning: "stubbornly refusing to change", options: ["yielding", "indulge", "exciting", "generosity"], correct: 0 },
    { word: "obscure", meaning: "not discovered or known about", options: ["famous", "generosity", "scarce", "neglect"], correct: 0 },
    { word: "obsolete", meaning: "no longer produced or used; out of date", options: ["stubborn", "modern", "unproductive", "oppose"], correct: 1 },
    { word: "onerous", meaning: "involving a great deal of effort or difficulty", options: ["persuade", "easy", "indulge", "thorough"], correct: 1 },
    { word: "ostentatious", meaning: "designed to impress or attract notice", options: ["originality", "alleviate", "modest", "abundance"], correct: 2 },
    { word: "parsimony", meaning: "extreme frugality; reluctance to spend", options: ["competent", "extraordinary", "generosity", "verbose"], correct: 2 },
    { word: "partisan", meaning: "prejudiced in favor of a particular cause", options: ["agitation", "stubborn", "persuade", "neutral"], correct: 3 },
    { word: "penchant", meaning: "a strong or habitual liking", options: ["dislike", "secure", "originality", "modern"], correct: 0 },
    { word: "perfunctory", meaning: "carried out with minimum effort", options: ["thorough", "malevolent", "intensify", "open"], correct: 0 },
    { word: "pernicious", meaning: "having a harmful effect in a gradual way", options: ["reckless", "harmless", "stubborn", "easy"], correct: 1 },
    { word: "placate", meaning: "to make someone less angry or hostile", options: ["originality", "disagree", "provoke", "changeable"], correct: 2 },
    { word: "platitude", meaning: "a remark that has been used too often", options: ["overlook", "harmful", "respect", "originality"], correct: 3 },
    { word: "plausible", meaning: "seeming reasonable or probable", options: ["subtle", "abundance", "unlikely", "virtuous"], correct: 2 },
    { word: "precarious", meaning: "not securely held; uncertain", options: ["aggravate", "secure", "oppose", "apathetic"], correct: 1 },
    { word: "prolific", meaning: "producing many works or results", options: ["unproductive", "modern", "extraordinary", "famous"], correct: 0 }
  ],
  synonyms: [
    { word: "astute", meaning: "having keen insight; shrewd", options: ["sharp", "kind", "gentle", "lazy"], correct: 0 },
    { word: "belligerent", meaning: "hostile and aggressive", options: ["friendly", "aggressive", "calm", "wise"], correct: 1 },
    { word: "candid", meaning: "truthful and straightforward", options: ["dishonest", "frank", "secretive", "vague"], correct: 1 },
    { word: "delineate", meaning: "to describe or portray precisely", options: ["confuse", "outline", "hide", "ignore"], correct: 1 },
    { word: "elaborate", meaning: "involving many carefully arranged parts", options: ["simple", "detailed", "brief", "plain"], correct: 1 },
    { word: "frugal", meaning: "sparing or economical with money", options: ["wasteful", "economical", "generous", "careless"], correct: 1 },
    { word: "gregarious", meaning: "fond of the company of others", options: ["shy", "sociable", "quiet", "lonely"], correct: 1 },
    { word: "hostile", meaning: "unfriendly; antagonistic", options: ["friendly", "antagonistic", "welcoming", "kind"], correct: 1 },
    { word: "imminent", meaning: "about to happen", options: ["distant", "impending", "unlikely", "past"], correct: 1 },
    { word: "jovial", meaning: "cheerful and friendly", options: ["sad", "cheerful", "angry", "serious"], correct: 1 },
    { word: "keen", meaning: "having or showing eagerness", options: ["dull", "eager", "lazy", "tired"], correct: 1 },
    { word: "lucid", meaning: "expressed clearly; easy to understand", options: ["confusing", "clear", "vague", "difficult"], correct: 1 },
    { word: "meticulous", meaning: "showing great attention to detail", options: ["careless", "careful", "sloppy", "hasty"], correct: 1 },
    { word: "nonchalant", meaning: "feeling or appearing casually calm", options: ["worried", "casual", "anxious", "stressed"], correct: 1 },
    { word: "opulent", meaning: "ostentatiously rich and luxurious", options: ["poor", "luxurious", "simple", "modest"], correct: 1 },
    { word: "placid", meaning: "not easily upset or excited", options: ["agitated", "calm", "angry", "nervous"], correct: 1 },
    { word: "quaint", meaning: "attractively unusual or old-fashioned", options: ["modern", "charming", "ugly", "new"], correct: 1 },
    { word: "robust", meaning: "strong and healthy; vigorous", options: ["weak", "strong", "frail", "delicate"], correct: 1 },
    { word: "serene", meaning: "calm, peaceful, and untroubled", options: ["chaotic", "peaceful", "loud", "disturbed"], correct: 1 },
    { word: "tenacious", meaning: "tending to keep a firm hold", options: ["weak", "persistent", "giving up", "lazy"], correct: 1 },
    { word: "ubiquitous", meaning: "present everywhere", options: ["rare", "widespread", "limited", "scarce"], correct: 1 },
    { word: "vivacious", meaning: "attractively lively and animated", options: ["dull", "lively", "boring", "tired"], correct: 1 },
    { word: "wary", meaning: "feeling or showing caution", options: ["trusting", "cautious", "careless", "naive"], correct: 1 },
    { word: "xenial", meaning: "of or concerning hospitality", options: ["rude", "hospitable", "unfriendly", "cold"], correct: 1 },
    { word: "zealous", meaning: "having great energy for a cause", options: ["lazy", "enthusiastic", "bored", "tired"], correct: 1 },
    { word: "affable", meaning: "friendly, good-natured, easy to talk to", options: ["rude", "friendly", "mean", "cold"], correct: 1 },
    { word: "benign", meaning: "gentle and kindly", options: ["harmful", "gentle", "cruel", "mean"], correct: 1 },
    { word: "cogent", meaning: "clear, logical, and convincing", options: ["weak", "convincing", "confusing", "illogical"], correct: 1 },
    { word: "dormant", meaning: "temporarily inactive", options: ["active", "inactive", "busy", "working"], correct: 1 },
    { word: "enigmatic", meaning: "difficult to interpret or understand", options: ["clear", "mysterious", "obvious", "simple"], correct: 1 },
    { word: "fervent", meaning: "having or displaying passionate intensity", options: ["cold", "passionate", "calm", "indifferent"], correct: 1 },
    { word: "genial", meaning: "friendly and cheerful", options: ["unfriendly", "cheerful", "sad", "mean"], correct: 1 },
    { word: "hackneyed", meaning: "overused and therefore lacking originality", options: ["original", "overused", "new", "fresh"], correct: 1 },
    { word: "incisive", meaning: "accurate and sharply focused", options: ["dull", "sharp", "blunt", "unclear"], correct: 1 },
    { word: "jaunty", meaning: "having a cheerful, confident manner", options: ["sad", "cheerful", "depressed", "gloomy"], correct: 1 },
    { word: "kinetic", meaning: "relating to or resulting from motion", options: ["still", "moving", "static", "stationary"], correct: 1 },
    { word: "languid", meaning: "lacking energy or vitality", options: ["energetic", "sluggish", "active", "vigorous"], correct: 1 },
    { word: "malleable", meaning: "easily influenced or pliable", options: ["rigid", "flexible", "hard", "stiff"], correct: 1 },
    { word: "nascent", meaning: "just coming into existence", options: ["dying", "emerging", "ending", "finished"], correct: 1 },
    { word: "ominous", meaning: "giving the impression that something bad will happen", options: ["good", "threatening", "positive", "hopeful"], correct: 1 },
    { word: "palpable", meaning: "able to be touched or felt", options: ["intangible", "tangible", "invisible", "unclear"], correct: 1 },
    { word: "quell", meaning: "to put an end to by force", options: ["encourage", "suppress", "start", "begin"], correct: 1 },
    { word: "raucous", meaning: "making a harsh, loud sound", options: ["quiet", "loud", "soft", "gentle"], correct: 1 },
    { word: "sagacious", meaning: "having good judgment; wise", options: ["foolish", "wise", "stupid", "ignorant"], correct: 1 },
    { word: "terse", meaning: "sparing in the use of words; abrupt", options: ["wordy", "brief", "long", "verbose"], correct: 1 },
    { word: "urbane", meaning: "courteous and refined in manner", options: ["rude", "refined", "crude", "rough"], correct: 1 },
    { word: "vehement", meaning: "showing strong feeling; forceful", options: ["mild", "forceful", "weak", "gentle"], correct: 1 },
    { word: "winsome", meaning: "attractive or appealing in a fresh way", options: ["unattractive", "charming", "ugly", "repulsive"], correct: 1 },
    { word: "exemplary", meaning: "serving as a desirable model", options: ["poor", "model", "bad", "terrible"], correct: 1 },
    { word: "yielding", meaning: "giving way under pressure", options: ["rigid", "flexible", "hard", "stiff"], correct: 1 },
    { word: "zestful", meaning: "characterized by great enthusiasm", options: ["dull", "enthusiastic", "boring", "lifeless"], correct: 1 },
    { word: "adept", meaning: "very skilled or proficient", options: ["unskilled", "skilled", "amateur", "inexperienced"], correct: 1 },
    { word: "blithe", meaning: "showing a casual lack of concern", options: ["worried", "carefree", "anxious", "troubled"], correct: 1 },
    { word: "clement", meaning: "mild in temper or behavior", options: ["harsh", "gentle", "cruel", "severe"], correct: 1 },
    { word: "deft", meaning: "neatly skillful and quick", options: ["clumsy", "skillful", "awkward", "slow"], correct: 1 },
    { word: "ebullient", meaning: "cheerful and full of energy", options: ["sad", "cheerful", "depressed", "gloomy"], correct: 1 },
    { word: "felicitous", meaning: "well chosen or suited to circumstances", options: ["inappropriate", "appropriate", "wrong", "unsuitable"], correct: 1 },
    { word: "glib", meaning: "fluent but insincere and shallow", options: ["sincere", "fluent", "honest", "deep"], correct: 1 },
    { word: "halcyon", meaning: "denoting a period of time that was peaceful", options: ["chaotic", "peaceful", "violent", "turbulent"], correct: 1 },
    { word: "idyllic", meaning: "extremely happy, peaceful, or picturesque", options: ["unpleasant", "peaceful", "ugly", "disturbing"], correct: 1 },
    { word: "jocose", meaning: "playful or humorous", options: ["serious", "playful", "sad", "grim"], correct: 1 },
    { word: "knowledgeable", meaning: "intelligent and well-informed", options: ["ignorant", "informed", "stupid", "unaware"], correct: 1 },
    { word: "limpid", meaning: "completely clear and transparent", options: ["cloudy", "clear", "murky", "opaque"], correct: 1 },
    { word: "magnanimous", meaning: "generous in forgiving", options: ["petty", "generous", "mean", "selfish"], correct: 1 },
    { word: "noble", meaning: "having fine personal qualities", options: ["ignoble", "dignified", "base", "low"], correct: 1 },
    { word: "optimistic", meaning: "hopeful and confident about the future", options: ["pessimistic", "hopeful", "negative", "doubtful"], correct: 1 },
    { word: "perspicacious", meaning: "having keen insight or discernment", options: ["dull", "insightful", "stupid", "blind"], correct: 1 },
    { word: "quintessential", meaning: "representing the most perfect example", options: ["imperfect", "perfect", "flawed", "inferior"], correct: 1 },
    { word: "resilient", meaning: "able to withstand or recover quickly", options: ["fragile", "tough", "weak", "brittle"], correct: 1 },
    { word: "sanguine", meaning: "optimistic especially in a difficult situation", options: ["pessimistic", "optimistic", "hopeless", "negative"], correct: 1 },
    { word: "tranquil", meaning: "free from disturbance; calm", options: ["chaotic", "calm", "noisy", "disturbed"], correct: 1 },
    { word: "unassuming", meaning: "not pretentious or arrogant", options: ["arrogant", "modest", "proud", "boastful"], correct: 1 },
    { word: "venerable", meaning: "accorded great respect", options: ["disrespected", "respected", "ignored", "scorned"], correct: 1 },
    { word: "wholesome", meaning: "conducive to health or moral well-being", options: ["harmful", "healthy", "bad", "toxic"], correct: 1 },
    { word: "exuberant", meaning: "filled with energy, excitement, and cheerfulness", options: ["dull", "lively", "boring", "lifeless"], correct: 1 },
    { word: "youthful", meaning: "having the appearance of being young", options: ["old", "young", "aged", "elderly"], correct: 1 },
    { word: "zealot", meaning: "a person who is fanatical and uncompromising", options: ["moderate", "fanatic", "calm", "reasonable"], correct: 1 },
    { word: "abundant", meaning: "existing in large quantities", options: ["scarce", "plentiful", "rare", "limited"], correct: 1 },
    { word: "brilliant", meaning: "exceptionally clever or talented", options: ["dull", "bright", "stupid", "dim"], correct: 1 },
    { word: "coherent", meaning: "logical and consistent", options: ["confused", "logical", "unclear", "mixed"], correct: 1 },
    { word: "diligent", meaning: "having or showing care in one's work", options: ["lazy", "hardworking", "careless", "negligent"], correct: 1 },
    { word: "elegant", meaning: "graceful and stylish in appearance", options: ["clumsy", "graceful", "awkward", "ugly"], correct: 1 },
    { word: "faithful", meaning: "loyal, constant, and steadfast", options: ["disloyal", "loyal", "unfaithful", "treacherous"], correct: 1 },
    { word: "genuine", meaning: "truly what it is said to be; authentic", options: ["fake", "authentic", "false", "artificial"], correct: 1 },
    { word: "harmonious", meaning: "forming a pleasing consistent whole", options: ["discordant", "balanced", "clashing", "jarring"], correct: 1 },
    { word: "immaculate", meaning: "perfectly clean, neat, or tidy", options: ["dirty", "spotless", "messy", "filthy"], correct: 1 },
    { word: "judicious", meaning: "having good judgment or sense", options: ["foolish", "wise", "stupid", "reckless"], correct: 1 },
    { word: "kindred", meaning: "similar in kind; related", options: ["different", "similar", "opposite", "unrelated"], correct: 1 },
    { word: "laudable", meaning: "deserving praise and commendation", options: ["blameworthy", "praiseworthy", "bad", "terrible"], correct: 1 },
    { word: "meritorious", meaning: "deserving reward or praise", options: ["unworthy", "deserving", "bad", "poor"], correct: 1 },
    { word: "noteworthy", meaning: "interesting or significant", options: ["insignificant", "significant", "boring", "trivial"], correct: 1 },
    { word: "orderly", meaning: "neatly and methodically arranged", options: ["messy", "organized", "chaotic", "disorganized"], correct: 1 },
    { word: "pristine", meaning: "in its original condition; unspoiled", options: ["damaged", "perfect", "ruined", "spoiled"], correct: 1 },
    { word: "quintessence", meaning: "the most perfect or typical example", options: ["worst", "essence", "failure", "inferior"], correct: 1 },
    { word: "rational", meaning: "based on reason or logic", options: ["irrational", "logical", "emotional", "unreasonable"], correct: 1 },
    { word: "steadfast", meaning: "resolutely firm and unwavering", options: ["wavering", "firm", "changing", "unstable"], correct: 1 },
    { word: "thorough", meaning: "complete with regard to every detail", options: ["incomplete", "complete", "partial", "superficial"], correct: 1 },
    { word: "upright", meaning: "honest and respectable", options: ["corrupt", "honest", "dishonest", "crooked"], correct: 1 },
    { word: "virtuous", meaning: "having high moral standards", options: ["immoral", "moral", "corrupt", "evil"], correct: 1 },
    { word: "worthy", meaning: "deserving effort, attention, or respect", options: ["unworthy", "deserving", "worthless", "insignificant"], correct: 1 },
    { word: "excellent", meaning: "extremely good; outstanding", options: ["poor", "outstanding", "bad", "terrible"], correct: 1 },
    { word: "yonder", meaning: "at some distance in the direction indicated", options: ["here", "distant", "near", "close"], correct: 1 },
    { word: "zenith", meaning: "the highest point reached", options: ["bottom", "peak", "low", "nadir"], correct: 1 }
  ]
};
